## code to prepare `univariate Gaussian CI X,Y,Z` dataset
#' Univariate Gaussian Conditional independent X,Y given Z
#'
#'
#' @format ## `who`
#' A data frame with 7,240 rows and 60 columns:
#' \describe{
#'   \item{X}{vector generated by Z}
#'   \item{Y}{scalar generated by Z}
#'   \item{Z}{confounder Z generated standard normal}
#' }
#' @source simulated
n <- 1000; p <- 1; q <- 1
X <- matrix(rnorm(n*p), nrow = n, ncol = p)
Y <- matrix(rnorm(n), nrow = n)
Z <- matrix(rnorm(n*q), nrow = n, ncol = q)
uni_gaussian_ci <- cbind(X, Y, Z)
usethis::use_data(uni_gaussian_ci, overwrite = TRUE)
